server:
  port: 1111
---
spring:
  application:
    name: servicio.catalogo 
  datasource:  
    url: jdbc:mysql://localhost:3306/expenses
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
    jpa:
      generate-ddl: true
      show_sql: true
 
 # Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:2222/eureka
  instance:
    preferIpAddress: true       