server:
  port: 3333
---
spring:
  application:
    name: servicio.cesta 
  datasource:  
    url: jdbc:mysql://localhost:3306/compra
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
    jpa:
      generate-ddl: true
      show_sql: true
 
 # Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:2222/eureka